services:
  application:
    build: ./application
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
    environment:
      - OPENAI_BASE_URL=$OPENAI_BASE_URL
      - OPENAI_API_BASE=$OPENAI_API_BASE
      - OPENAI_API_KEY=$OPENAI_API_KEY
    volumes:
      - "./data:/tmp/data"
    logging:
      options:
        max-size: "128k"
        max-file: "1"
      driver: json-file
